### ISSUE TITLE
[Task]: Release `1.2.1` tracker

### ISSUE THREAD

**Issue by joe733** [rustdesk/rustdesk#4300]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

> _It's been a year from the last stable release. I thought it'd be good idea to track the next one._

**Projects**:

Checked box implies project is closed.

- [ ] `#2` [Low latency optimization](https://github.com/users/rustdesk/projects/2)
- [ ] `#3` [Adaptive network rate control](https://github.com/users/rustdesk/projects/3)
- [ ] `#6` [Better Windows/Mac/Linux integration](https://github.com/users/rustdesk/projects/6)
- [ ] `#8` [UDP punch hole](https://github.com/users/rustdesk/projects/8)
- [ ] `#9` [Virtual Display if no physical one on Windows and Linux](https://github.com/users/rustdesk/projects/9)
- [ ] `#10` [Windows drivers etc](https://github.com/users/rustdesk/projects/10)
- [ ] `#12` [Optimize mobile experience, better gesture design, raw keyboard](https://github.com/users/rustdesk/projects/12)
- [ ] `#13` [better file transfer support (drag, copy/paste, incremental sync)](https://github.com/users/rustdesk/projects/13)
- [ ] `#15` [more strong password (two passwords as TV/AnyDesk, TPM etc)](https://github.com/users/rustdesk/projects/15)

**Issues & PRs**:

> Maintainers can help fill up this section.
