### ISSUE TITLE
[Task]: config file robustness and compatibility

### ISSUE THREAD

**Issue by rustdesk** [rustdesk/rustdesk#4388]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- [ ] add a field which is not present in config.rs
- [ ] add a valid field name but value is invalid
- [ ] add test for this
- [ ] add cargo test to CI
- [ ] Some one reported Id changed when change from 1.1.9 to 1.2.0, I guess it is related. test again after change.

**Comment by rustdesk** [comment]
@21pages
